ALTER TABLE "PlayerExternalId"
ADD COLUMN "matchMethod" TEXT NOT NULL DEFAULT 'STABLE_ID',
ADD COLUMN "confidence" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "verifiedAt" TIMESTAMP(3);

ALTER TABLE "ProviderSyncRun"
ADD COLUMN "stableIdMatches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "fallbackMatches" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "ambiguousMatches" INTEGER NOT NULL DEFAULT 0;
