import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { generateReport } from "@/features/reports/actions";
import { FormSubmit } from "@/components/form-submit";
import { TeamNav } from "@/components/team-nav";
import { getFantasyWeek } from "@/lib/fantasy-week";

export default async function ReportPage({params}:{params:Promise<{teamId:string}>}){const{season:SEASON,week:WEEK}=getFantasyWeek();const user=await requireUser();const{teamId}=await params;const team=await db.team.findFirst({where:{id:teamId,userId:user.id},include:{weeklyReports:{where:{season:SEASON,week:WEEK},take:1}}});if(!team)notFound();const report=team.weeklyReports[0];return <main className="mx-auto max-w-4xl p-5 md:p-8"><p className="text-sm text-emerald-300">{team.name} · Week {WEEK}</p><h1 className="mb-5 text-3xl font-bold">Weekly team report</h1><TeamNav teamId={team.id} active="report"/><form action={generateReport} className="mb-5"><input type="hidden" name="teamId" value={team.id}/><input type="hidden" name="season" value={SEASON}/><input type="hidden" name="week" value={WEEK}/><FormSubmit pending="Analyzing…">Generate weekly report</FormSubmit></form>{report?<><section className="card mb-4 grid gap-4 p-5 sm:grid-cols-3"><Metric label="Team grade" value={report.grade}/><Metric label="Strongest" value={report.strongestPosition}/><Metric label="Weakest" value={report.weakestPosition}/></section><section className="card p-6"><p className="text-xs font-bold uppercase tracking-wider text-violet-300">AI roster analysis</p><p className="mt-4 leading-7">{report.summary}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Fact label="Riskiest starter" value={report.riskiestStarter}/><Fact label="Best bench option" value={report.bestBenchOption}/></div></section></>:<section className="card p-8 text-center muted">Save player projections, then generate your first report.</section>}</main>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>};function Fact({label,value}:{label:string;value:string|null}){return <div className="rounded-xl bg-[#0a1019] p-4"><p className="text-xs muted">{label}</p><p className="mt-1 font-bold">{value??"Not available"}</p></div>}
