ALTER TYPE "Position" ADD VALUE 'TQB' AFTER 'QB';
ALTER TYPE "Position" ADD VALUE 'DT' AFTER 'TE';
ALTER TYPE "Position" ADD VALUE 'DE' AFTER 'DT';
ALTER TYPE "Position" ADD VALUE 'LB' AFTER 'DE';
ALTER TYPE "Position" ADD VALUE 'CB' AFTER 'LB';
ALTER TYPE "Position" ADD VALUE 'S' AFTER 'CB';
ALTER TYPE "Position" ADD VALUE 'P' AFTER 'K';
ALTER TYPE "Position" ADD VALUE 'HC' AFTER 'P';

ALTER TYPE "LineupSlot" ADD VALUE 'TQB' AFTER 'QB';
ALTER TYPE "LineupSlot" ADD VALUE 'RB_WR' AFTER 'RB';
ALTER TYPE "LineupSlot" ADD VALUE 'OP' AFTER 'WR_TE';
ALTER TYPE "LineupSlot" ADD VALUE 'DT' AFTER 'SUPERFLEX';
ALTER TYPE "LineupSlot" ADD VALUE 'DE' AFTER 'DT';
ALTER TYPE "LineupSlot" ADD VALUE 'LB' AFTER 'DE';
ALTER TYPE "LineupSlot" ADD VALUE 'DL' AFTER 'LB';
ALTER TYPE "LineupSlot" ADD VALUE 'CB' AFTER 'DL';
ALTER TYPE "LineupSlot" ADD VALUE 'S' AFTER 'CB';
ALTER TYPE "LineupSlot" ADD VALUE 'DB' AFTER 'S';
ALTER TYPE "LineupSlot" ADD VALUE 'DP' AFTER 'DB';
ALTER TYPE "LineupSlot" ADD VALUE 'P' AFTER 'K';
ALTER TYPE "LineupSlot" ADD VALUE 'HC' AFTER 'P';
ALTER TYPE "LineupSlot" ADD VALUE 'IR' AFTER 'BENCH';

ALTER TABLE "LeagueSettings" ADD COLUMN "rosterMaximums" JSONB NOT NULL DEFAULT '{}';
